Refactoring security 2
superpowerlabs/copper-leaderboard pull request #83
Opened 2022-09-22 14:32 UTC by yacc

### 1/ Remove "unsafe-eval" directive
I removed the "unsafe-eval" directive b/c it's unsafe:
- the CSP errors that this addressed were generated only in development (production works wo this directive) b/c of a bug in the webconfig file
- fixed webconfig file, that wasn't taking the `config.devtool = "inline-source-map";` into account when running `ENV=development pnpm build; pnpm start`, b/c webconfig was expecting to see "development" as an arg only not an ENV var.
### 2/ Move nonce for index to its own middleware

2022-09-22 16:03 UTC, sullof commented on server/applyNonce/index.js
> +      case "bundle":
The files & folders that must go next and be read from the static path may be a setting passed by app.js, like
```
applyNonce(app, {
   static: [ 
       "favicon.png",
       "favicon.ico",
       "styles",
       "all",
       "images",
       "bundle"
    ]
});
```
This way we can set it differently for any website.

2022-09-22 16:07 UTC, yacc commented on server/applyNonce/index.js
> +      case "bundle":
I'll fix this, good suggestion :-)

2022-09-22 17:08 UTC, sullof approved these changes
It looks good to me

2022-09-22 17:23 UTC, yacc commented
@sullof Hmmm, I just noticed that I'm getting an error when building in production, it still build and loads, and I don't think ESlint was triggered before the webpack.config fix. 
<img width="849" alt="Screen Shot 2022-09-22 at 6 21 35 PM" src="https://user-images.githubusercontent.com/46958/191811631-7d3238f4-9be9-4114-a536-d54dbc05aa50.png">

But I'll wait until I fix this to merge to main.

2022-09-25 17:51 UTC, sullof commented
Is it ready to merge?

2022-09-27 16:13 UTC, sullof commented
There is an issue here. The app reload the animated GIFs again and again, consuming bandwidth for nothing. It must be fixed

2022-09-27 16:32 UTC, sullof requested changes
The app reloads the animated GIFs forever. There is probably an error in the way they are rendered by React

2022-09-28 13:29 UTC, yacc commented
@sullof  the constant reload is not caused by the GIFs (they don't get downloaded continuously from s3). You can check the network tab and you'll see that they're downloaded only ounce. I also removed the GIFs from the page and I'm still seeing that the page seems to be always loading. I'm investigating why.

2022-09-28 13:31 UTC, yacc commented
I did a few test and realized that the loading icon on the tab was running because the page couldn't load the favicon...
![Screen Shot 2022-09-28 at 3 20 26 PM](https://user-images.githubusercontent.com/46958/192791375-f5e53956-5a6a-4dfa-a1d4-eff05a25dc91.png)
I fixed the CSP rules and now it's fine.
Good catch

2022-09-28 16:08 UTC, merged